import { MOCK_ACTIVITY } from '../data/mockActivity';

/**
 * Core handover engine.
 * Rules:
 * 1. Filter events: shift_start <= timestamp < shift_end
 * 2. Deduplicate by (source, record_id) — keep the latest timestamp entry
 * 3. Classify into 4 buckets based on final status
 * 4. Deterministic: same inputs → same output
 */

const STATUS_MAP = {
  Completed: 'completed',
  'In Progress': 'inProgress',
  Blockers: 'blockers',
  'Watch-list': 'watchlist',
};

/**
 * @param {string} shiftStart  ISO string (inclusive)
 * @param {string} shiftEnd    ISO string (exclusive)
 * @param {string[]} sources   Array of source names to include
 * @param {object[]} [customActivity]  Override for testing
 * @returns {{ items: object[], counts: object, warnings: string[] }}
 */
export function generateHandover(shiftStart, shiftEnd, sources, customActivity) {
  const warnings = [];
  const activity = customActivity || MOCK_ACTIVITY;

  const start = new Date(shiftStart).getTime();
  const end = new Date(shiftEnd).getTime();

  if (isNaN(start) || isNaN(end)) {
    warnings.push('Invalid shift window timestamps — no events loaded.');
    return { items: [], counts: { completed: 0, inProgress: 0, blockers: 0, watchlist: 0 }, warnings };
  }

  if (start >= end) {
    warnings.push('Shift start must be before shift end.');
    return { items: [], counts: { completed: 0, inProgress: 0, blockers: 0, watchlist: 0 }, warnings };
  }

  // Step 1: Filter by time window and selected sources
  const filtered = activity.filter(evt => {
    const ts = new Date(evt.timestamp).getTime();
    const inWindow = ts >= start && ts < end;
    const inSources = sources.includes(evt.source);
    return inWindow && inSources;
  });

  if (filtered.length === 0) {
    warnings.push('No events found in the selected shift window for the chosen sources.');
  }

  // Step 2: Deduplicate by (source, record_id) — keep latest timestamp
  const dedupeMap = new Map();
  for (const evt of filtered) {
    const key = `${evt.source}::${evt.record_id}`;
    const existing = dedupeMap.get(key);
    if (!existing || new Date(evt.timestamp) > new Date(existing.timestamp)) {
      dedupeMap.set(key, evt);
    }
  }

  const deduplicated = Array.from(dedupeMap.values());

  // Step 3: Sort by timestamp descending within each group
  deduplicated.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

  // Step 4: Classify
  const classified = {
    completed: [],
    inProgress: [],
    blockers: [],
    watchlist: [],
  };

  for (const evt of deduplicated) {
    const bucket = STATUS_MAP[evt.status] || 'watchlist';
    classified[bucket].push(evt);
  }

  const counts = {
    completed: classified.completed.length,
    inProgress: classified.inProgress.length,
    blockers: classified.blockers.length,
    watchlist: classified.watchlist.length,
  };

  return {
    items: deduplicated,
    classified,
    counts,
    warnings,
    totalEvents: filtered.length,
    dedupedCount: deduplicated.length,
    duplicatesRemoved: filtered.length - deduplicated.length,
  };
}

/**
 * Generate a Slack-formatted summary of the handover
 */
export function generateSlackSummary(handover, shiftStart, shiftEnd, userName) {
  const fmt = (iso) => new Date(iso).toLocaleString('en-GB', {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC',
  }) + ' UTC';

  const lines = [
    `*📋 Shift Handover Note*`,
    `*Shift:* ${fmt(shiftStart)} → ${fmt(shiftEnd)}`,
    `*Created by:* ${userName}`,
    ``,
    handover.classified?.completed?.length
      ? `*✅ Completed (${handover.classified.completed.length}):*\n` +
        handover.classified.completed.slice(0, 3).map(i => `  • ${i.summary} _(${i.record_id})_`).join('\n')
      : `*✅ Completed:* Nothing to report`,
    ``,
    handover.classified?.inProgress?.length
      ? `*🔄 In Progress (${handover.classified.inProgress.length}):*\n` +
        handover.classified.inProgress.slice(0, 3).map(i => `  • ${i.summary} _(${i.record_id})_`).join('\n')
      : `*🔄 In Progress:* Nothing to report`,
    ``,
    handover.classified?.blockers?.length
      ? `*🚨 Blockers (${handover.classified.blockers.length}):*\n` +
        handover.classified.blockers.map(i => `  • ${i.summary} _(${i.record_id})_`).join('\n')
      : `*🚨 Blockers:* None`,
    ``,
    handover.classified?.watchlist?.length
      ? `*👁 Watch-list (${handover.classified.watchlist.length}):*\n` +
        handover.classified.watchlist.map(i => `  • ${i.summary} _(${i.record_id})_`).join('\n')
      : `*👁 Watch-list:* Nothing`,
    ``,
    `_Generated by ShiftFlow AI_`,
  ];

  return lines.join('\n');
}
