import jsPDF from 'jspdf';

function fmtDate(iso) {
  return new Date(iso).toLocaleString('en-GB', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZone: 'UTC',
  }) + ' UTC';
}

export async function exportHandoverPDF(handover, shiftStart, shiftEnd, userName) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PAGE_W = 210;
  const MARGIN = 18;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  let y = 20;

  const checkPage = (needed = 10) => {
    if (y + needed > 280) {
      doc.addPage();
      y = 20;
    }
  };

  // Header bar
  doc.setFillColor(10, 15, 30);
  doc.rect(0, 0, PAGE_W, 36, 'F');
  doc.setTextColor(20, 184, 166);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('ShiftFlow AI', MARGIN, 16);
  doc.setFontSize(11);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text('Shift Handover Note', MARGIN, 25);

  y = 46;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Shift: ${fmtDate(shiftStart)} → ${fmtDate(shiftEnd)}`, MARGIN, y);
  y += 6;
  doc.text(`Created by: ${userName}   |   Generated: ${fmtDate(new Date().toISOString())}`, MARGIN, y);
  y += 4;
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  if (handover.summary) {
    doc.setFontSize(9);
    doc.setTextColor(200, 210, 220);
    doc.setFont('helvetica', 'italic');
    const lines = doc.splitTextToSize(handover.summary, CONTENT_W);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 6;
  }

  const SECTIONS = [
    { key: 'completed', label: '✓  COMPLETED', color: [34, 197, 94] },
    { key: 'inProgress', label: '↺  IN PROGRESS', color: [59, 130, 246] },
    { key: 'blockers', label: '⚠  BLOCKERS / ESCALATIONS', color: [239, 68, 68] },
    { key: 'watchlist', label: '◉  WATCH-LIST', color: [245, 158, 11] },
  ];

  for (const section of SECTIONS) {
    checkPage(20);
    const items = handover.classified?.[section.key] || [];

    // Section header
    doc.setFillColor(...section.color, 20);
    doc.roundedRect(MARGIN, y - 4, CONTENT_W, 10, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...section.color);
    doc.text(`${section.label}   (${items.length})`, MARGIN + 3, y + 2);
    y += 12;

    if (items.length === 0) {
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(100, 116, 139);
      doc.text('Nothing to report', MARGIN + 4, y);
      y += 10;
      continue;
    }

    for (const item of items) {
      checkPage(18);
      doc.setFillColor(17, 24, 39);
      doc.roundedRect(MARGIN, y - 3, CONTENT_W, 14, 1.5, 1.5, 'F');

      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(230, 240, 250);
      const summaryLines = doc.splitTextToSize(item.summary, CONTENT_W - 6);
      doc.text(summaryLines, MARGIN + 3, y + 2);

      const metaY = y + 2 + summaryLines.length * 4;
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(
        `${item.source}: ${item.record_id}   •   ${fmtDate(item.timestamp)}   •   ${item.assignee || ''}`,
        MARGIN + 3, metaY
      );
      y += summaryLines.length * 4 + 12;
    }
    y += 4;
  }

  // Footer
  doc.setFontSize(7.5);
  doc.setTextColor(60, 80, 100);
  doc.text(
    'Generated by ShiftFlow AI — Every item is source-grounded and deduplicated.',
    MARGIN, 292
  );

  doc.save(`ShiftFlow_Handover_${new Date(shiftStart).toISOString().slice(0, 10)}.pdf`);
}
